#!/bin/bash

CURSIVE_HOME=.
DATA_HOME=../designs

#WIDTH=1575
#HEIGHT=2000
#SIDE=300
#TOP=400
#DRAW=800

BASE=$1
WIDTH=${2:-500}

INPUT_SVG=$DATA_HOME/originals/$BASE.svg 
GENERATED_GCODE=$DATA_HOME/gcodes/$BASE.gcode 
CHECK_SVG=$DATA_HOME/checks/$BASE.check.svg
POINTS=$DATA_HOME/points/$BASE.d
VIZ=$DATA_HOME/visualisation/$BASE.html


source `which virtualenvwrapper.sh`
workon cursivedata

python $CURSIVE_HOME/convert.py --width $WIDTH --pyconf conf --input $INPUT_SVG --output $GENERATED_GCODE

echo "Converting $INPUT_SVG to $GENERATED_GCODE"
python gcode_to_svg.py --pyconf conf --input $GENERATED_GCODE --output $CHECK_SVG

deactivate

echo "path planning $GENERATED_GCODE to $POINTS"
../planner/plan.py --file $GENERATED_GCODE --out $POINTS

echo "creating path visualisation in $VIZ"
../planner/visualise.py --file $POINTS --out $VIZ
